### ISSUE TITLE
[Suggestion] Add auto-update support

### ISSUE THREAD

**Issue by AdamCalculator** [WildFyr16/zelda-music#3]
hello, I am the developer of the [DynamicPack](https://modrinth.com/mod/dynamicpack) mod which allows resource packs to update automatically if their owner configures one single file

This is what it should look like.
name: `dynamicmcpack.json`
```json
{
    "formatVersion": 1,
    "current": {
      "version_number": "1.20.4-3"
    },
    "remote": {
      "game_version": "1.20.4",
      "modrinth_project_id": "zelda-music",
      "type": "modrinth"
    }
}
```

![2024-03-25_10 08 02](https://github.com/Faithful-Resource-Pack/Faithful-Java-64x/assets/156993728/870573e5-8578-4fb9-8452-7b4b7a678021)

**Comment by WildFyr16** [comment]
Oh this is very cool, I will look into this for the next release

**Comment by WildFyr16** [comment]
Added in release [1.20.4-4](https://github.com/WildFyr16/zelda-music/releases/tag/1.20.4-4).
