### ISSUE TITLE
DynamicPack not work

### ISSUE THREAD

**Issue by AdamCalculator** [WildFyr16/zelda-music#4]
### JSON Specification not support comments!

![image](https://github.com/WildFyr16/zelda-music/assets/156993728/c31c346e-8292-4c3f-bcf6-76efecaa0b99)

**Comment by AdamCalculator** [comment]
![image](https://github.com/WildFyr16/zelda-music/assets/156993728/32f69994-e816-4318-9c8a-f968ff583a17)

**Comment by WildFyr16** [comment]
Hmmm, it must not support json with comments? Very strange because every other jsoj related file I have ever used has. I am looking into this.

**Comment by AdamCalculator** [comment]
fixed
